version: "2"

services:
    mpserver:
        build:
            context: ./
        env_file: .env
        ports:
            - 8091:80

    tests:
        depends_on:
            - mpserver
        build:
            context: ./
        entrypoint: ["go", "test", "./..."]
