version: "2"

services:
    mpserver:
        build:
            context: ./
        environment:
            S3_ENDPOINT: "http://localstack:4572"
            TOKEN_ENDPOINT: "http://token_mock"
        env_file: .env
        ports:
            - 8091:80

    tests:
        depends_on:
            - mpserver
            - localstack
            - token_mock
        build:
            context: ./
        entrypoint: ["go", "test", "./..."]

    localstack:
        image: localstack/localstack
        environment:
            SERVICES: "s3"
        ports:
            - 4572:4572

    token_mock:
        build:
            context: ./mocks/token_endpoint
