version: "2"

services:
    mpserver:
        build:
            context: ./
        environment:
            S3_ENDPOINT: "http://localstack:4572"
        env_file: .env
        ports:
            - 8091:80

    tests:
        depends_on:
            - mpserver
        build:
            context: ./
        entrypoint: ["go", "test", "./..."]

    localstack:
        image: localstack/localstack
        environment:
            SERVICES: "s3"
        ports:
            - 4572:4572
