version: "2"

services:
    server:
        build:
            context: ./
        environment:
            TOKEN_ENDPOINT: "https://tokens.indieauth.com/token" ## used to validate tokens
            MEDIA_ENDPOINT: "http://mpserver/media" ## used for q=config
            S3_ENDPOINT: "http://localstack:4572" ## DEV
            S3_EVENTS_KEY: "jay" ## prefix for event files
            S3_EVENTS_BUCKET: "events.funabashi.co.uk"
            S3_MEDIA_BUCKET: "media.funabashi.co.uk"
            BASE_URL: "http://mpserver/" ## used when saving posts + events metadata
            SITE_URL: "https://jay.funabashi.co.uk/"
            DATABASE_URL: "postgresql://postgres:example@db:5432?sslmode=disable"
            PORT: 8091
        depends_on:
          - db
          - localstack
        env_file: .env
        ports:
            - 8091:8091
        entrypoint: ["./scripts/run_local.sh"]
        volumes:
          - ./view:/go/src/github.com/j4y_funabashi/inari-micropub/view

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example

    localstack:
        image: localstack/localstack
        environment:
            SERVICES: "s3"
            DEFAULT_REGION: "eu-west-1"
            DATA_DIR: "/tmp/localstack/data"
            USE_SSL: "false"
        ports:
            - 4572:4572
